### ISSUE TITLE
Partner Authentication command is not working with parameters.

### ISSUE THREAD

**Issue by muhammedowais** [woocommerce/qit-cli#106]
I am trying to use the Partner Authentication command with the _`--user`_ and _`--application_password`_ options, but it is not working. 

**When I run this command:**
`./vendor/bin/qit partner:add --user="MYUSERNAME" --application_password="MYAPPPASS"`

**I get this error:**
The "--user" option does not exist.

**Comment by Luc45** [comment]
What's the output of `./vendor/bin/qit partner:add --help`?

Should be like this
![image](https://github.com/woocommerce/qit-cli/assets/9341686/56e047a9-bd57-4979-bc5f-872014301c3a)

**Comment by Luc45** [comment]
@muhammedowais and also the output of `./vendor/bin/qit` (without any parameters)

**Comment by muhammedowais** [comment]
@Luc45 here is the output of `./vendor/bin/qit partner:add --help` 

![Capture444](https://github.com/woocommerce/qit-cli/assets/30554053/e2efb6c1-6f65-44e1-9974-761406071a04)

And the output of `./vendor/bin/qit`

![Capture5555](https://github.com/woocommerce/qit-cli/assets/30554053/c036f636-19c2-4e22-970a-05ee6ef2f19a)

**Comment by Luc45** [comment]
@muhammedowais Ah, I see what's happening.

When you use QIT for the very first time, it will prompt you for the Partner account/password.

If you look at the last line it's asking you for the username/email of your Partner account. Just follow the flow and you should authenticate.

**Comment by muhammedowais** [comment]
@Luc45, so how can I use it in the CI/CD pipeline with the prompts?

**Comment by Luc45** [comment]
@muhammedowais We have some example workflows here that you can use as a base: https://woocommerce.github.io/qit-documentation/#/workflows/getting-started

In CI/CD you can do this for now:
```
QIT_DISABLE_ONBOARDING=yes ./vendor/bin/qit partner:add --user="MYUSERNAME" --application_password="MYAPPPASS"
```

And I just opened a PR to make QIT a bit smarter and not showing the onboarding at all if running in a CI context.

**Comment by muhammedowais** [comment]
@Luc45, thank you! Finally, it's working.

**Comment by muhammedowais** [comment]
@Luc45 I'm still not able to authenticate. I just got one step closer with your last solution. 

Here is the current issue:

![Capture](https://github.com/woocommerce/qit-cli/assets/30554053/ad18a82b-7904-46d4-8de6-51c72f854b1c)

**Comment by Luc45** [comment]
@muhammedowais What are you using as the "Application Password"?

**It has to be the application password generated during the ONBOARDING flow.**

- Keep the onboarding enabled
- Follow the onboarding flow as expected
- You will be given a link where you can generate the QIT application password
- Follow the link to generate it, copy it to a safe place to use it to authenticate on CI

**Comment by muhammedowais** [comment]
@Luc45 Ah, I skipped the onboarding step and created the application password manually from Woo.com.

Now, I have successfully run the QIT in the CI pipeline.

Thank you, @Luc45, for your invaluable assistance. You really saved the day!

**Comment by Luc45** [comment]
I'm glad it worked out. I'm closing this for now, feel free to reopen if needed.

> I skipped the onboarding step and created the application password manually from Woo.com.

Ah yes, that won't work.

It has to be QIT Application Password _(we'll be renaming it to QIT Token to reduce confusion)_, which is way more secure as it can only be used to view and start test runs, and nothing else, so if an attacker gets a hold of your token it's way less of a problem as if it were a regular application password.
