### ISSUE TITLE
Clean up implicit conversion PHP Deprecated warning in ParallelOutput.php

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/qit-cli#127]
When running self tests, I get the following warning on the console:

`PHP Deprecated:  Implicit conversion from float 636.5710530281067 to int loses precision in /qit-cli/_tests/ParallelOutput.php on line 70`

Currently running the following:

```
PHP 8.3.2 (cli) (built: Jan 16 2024 13:46:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.2, Copyright (c), by Zend Technologies
```

It doesn't impact anything, but could be worth cleaning up as a small task.

**Comment by Luc45** [comment]
Can you please confirm this is still happening on latest trunk? I've seen this and fixed it while working on the rename test type PR.

**Comment by zhongruige** [comment]
> Can you please confirm this is still happening on latest trunk? I've seen this and fixed it while working on the rename test type PR.

Just tried again on the latest trunk:

```
PHP Deprecated:  Implicit conversion from float 0.002132892608642578 to int loses precision in /qit-cli/_tests/ParallelOutput.php on line 70
```
