### ISSUE TITLE
--woocommerce_version option fails when running with run:security

### ISSUE THREAD

**Issue by puntope** [woocommerce/qit-cli#136]
When testing QIT in our workflows the QIT security against `WC 8.7.0-beta.2` it throws an error. For the rest of the runners, it works, but not for security.

**Testing steps:**

Run this command for running QIT

```
qit run:security google-listings-and-ads --woocommerce_version=8.7.0-beta.2
```

See it throws an error.

**Screenshots**

![image](https://github.com/woocommerce/qit-cli/assets/17435/85c294df-a9b4-4be9-9175-6febccb6a1d2)

**Comment by Luc45** [comment]
Hi @puntope, the Security test doesn't accept a `--woocommerce_version` parameter because this test type doesn't use WooCommerce at all, just your plugin files.

**Comment by puntope** [comment]
I will close this then as it seems to be expected. Thanks @Luc45
