### ISSUE TITLE
Add `woo:validate-zip <path>` command to docs

### ISSUE THREAD

**Issue by rcstr** [woocommerce/qit-cli#169]
add to our  [documentation](https://qit.woo.com/docs/category/managed-tests), I think under "Managed Tests" might make the most sense, and we can mention the files and folder structures this checks for to provide more context for the user, then in a follow up task, add a link to the docs in the results. Let me know your thoughts!

_Originally posted by @zhongruige in https://github.com/woocommerce/qit-cli/pull/163#pullrequestreview-2053904117_

**Comment by rcstr** [comment]
# Validating ZIP Files
The `woo:validate-zip` command ensures the contents of a local ZIP file meet specific criteria.

### Command Usage:
```bash
qit woo:validate-zip <path-to-zip-file>
```

### Example:

```bash
qit woo:validate-zip /path/to/my-extension.zip
```

### Validation Criteria:

`woo:validate-zip` command checks the following:

- Ensures no invalid files (e.g., system files) are present. The list of invalid files includes:
  - `Thumbs.db`, `Thumbs.db:encryptable`
  - `Desktop.ini`, `desktop.ini`
  - `ehthumbs.db`, `ehthumbs_vista.db`
  - `$RECYCLE.BIN/`
  - `~`, `.directory`
  - .`DS_Store`, `.AppleDouble`, `.LSOverride`, `.Spotlight-V100`, `.Trashes`, `.fseventsd`
- Ensures that the ZIP file is not corrupted or generated incorrectly (e.g., by macOS Archive Utility).

### Example Folder Structure
Here is an example of a valid folder structure for a ZIP file:

```perl
my-extension.zip
├── my-extension/
│   ├── my-extension.php
│   ├── includes/
│   │   └── class-my-extension.php
│   └── assets/
│       └── css/
│           └── style.css
```

**Comment by rcstr** [comment]
@zhongruige—I have added a draft to document this command (https://github.com/woocommerce/qit-cli/issues/169#issuecomment-2113193095). Let me know what you think. 

Besides where to add, I think https://qit.woo.com/docs/cli/useful-commands or https://qit.woo.com/docs/category/local-test-environment will fit best. What do you think?

**Comment by zhongruige** [comment]
I really like that @rcstr, and I think that is perfect for the documentation.

> where to add

Good question--I think adding it under https://qit.woo.com/docs/cli/useful-commands makes the most sense. We can probably then break that page out with meaningful headers for each command, something like:

```markdown

## List extensions

Lorem ipsum

## List tests

Lorem ipsum

## View a single test

Lorem ipsum

## Validate zip

Lorem ipsum

```

It doesn't have to be the exact order as above, feel free to re-arrange in the order you feel makes sense, but this will help to make the document easier to navigate and we get the nice bonus side bar navigation on the right-hand size, like on this page: https://qit.woo.com/docs/environment/getting-started

**Comment by rcstr** [comment]
@zhongruige I have opened a PR to update the docs https://github.com/woocommerce/qit-documentation/pull/32
