### ISSUE TITLE
Invalid zip contents despite correct zip file

### ISSUE THREAD

**Issue by alewolf** [woocommerce/qit-cli#44]
When I try to upload my zip file for testing with `qit run:security woocommerce-pixel-manager --zip=woocommerce-pixel-manager.zip` I get the error: 

`Invalid zip contents. Please make sure that the zip contains the plugin folder at the root level. Expected to find directory: woocommerce-pixel-manager`

The zip file is correctly formatted. It contains the `woocommerce-pixel-manager` folder. And it also works fine when I upload the file for a new release. It gets processed by the PBS without problems. 

This seems to be a bug. 

Let me know if you need more information.

**Comment by Luc45** [comment]
Thank you for the bug report, @alewolf

This will likely be fixed on https://github.com/woocommerce/qit-cli/pull/46, but if you'd like to share the zip, I could confirm it.

You could either generate the Zip index and share it here with `unzip -l woocommerce-pixel-manager.zip > index.txt`, or send the zip to qit@woocommerce.com referencing this issue.

**Comment by alewolf** [comment]
@Luc45 Ok. I've sent you an email with a download link to qit@woocommerce.com. 

Let me know if you need anything else.

**Comment by Luc45** [comment]
Thanks for sending the zip, I can confirm that it fits one of the scenarios we are aware of, and the fix we are working on will work for you, too. It should be fixed by early next week.

**Comment by Luc45** [comment]
@alewolf jfyi QIT CLI 0.3.4 is out.

> Resolved an issue that caused QIT to incorrectly identify certain valid zip files as invalid.

**Comment by alewolf** [comment]
@Luc45 Great! I can confirm that it works for me.
