### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by alewolf** [woocommerce/qit-cli#45]
On https://woocommerce.github.io/qit-documentation/#/cli/running-tests you have the following spelling mistake:

"For example, to run end-to-end tests against your local build, you'd **fun** the following command:"

**Comment by zhongruige** [comment]
Thanks so much for flagging this @alewolf! Apologies for the delay following up on this--the typo has now been fixed:

<img width="837" alt="Screenshot 2023-07-10 at 20 23 28" src="https://github.com/woocommerce/qit-cli/assets/71906536/7e143b88-94af-49c7-91e4-7fd78a972e7f">

Closing this thread, but do let us know if there's anything else. Thank you!
