### ISSUE TITLE
exclude vendor directory for PHPStan test

### ISSUE THREAD

**Issue by alewolf** [woocommerce/qit-cli#47]
When running the PHPStan test, I get many file errors from my plugin's `/vendor/` directory. 

In my opinion, that directory should be excluded, or we should have the option to exclude it.

**Comment by Luc45** [comment]
Thanks for the suggestion, I agree we should ignore it. We'll probably look into it next week.

**Comment by Luc45** [comment]
Done @alewolf , thanks for the feedback.
