### ISSUE TITLE
exclude wc_implode_html_attributes, wc_get_notice_data_attr, and other similar funcions from the WordPress.Security.EscapeOutput.OutputNotEscaped

### ISSUE THREAD

**Issue by oscargare** [woocommerce/qit-cli#50]
Hi,
The WooCommerce core functions that already escape the output, like `wc_implode_html_attributes`, or `wc_get_notice_data_attr`, **should not** trigger `WordPress.Security.EscapeOutput.OutputNotEscaped` error.

**Comment by Luc45** [comment]
Thanks for your feedback, @oscargare.

We use the same escaping and sanitizing rules as [WooCommerce Core PHPCS file](https://github.com/woocommerce/woocommerce-sniffs/blob/trunk/src/WooCommerce-Core/ruleset.xml#L18-L28), so we should be mostly covered.

I have checked `wc_implode_html_attributes` and `wc_get_notice_data_attr` and I agree they can be added as Escaping Functions, I'll take this on this sprint.

**Comment by Luc45** [comment]
Done @oscargare , thanks for the feedback.

**Comment by oscargare** [comment]
Thank you,
When will this change be available in the WooCommerce.com Partner Developer dashboard?
