### ISSUE TITLE
Is there a way to suppress certain security warnings?

### ISSUE THREAD

**Issue by alewolf** [woocommerce/qit-cli#52]
I have a few REST endpoints that must be public. 

For example, using a REST endpoint, my plugin receives tracking data from guest visitors. It passes the tracking data through a server-to-server protocol to statistics and marketing platforms, like Google Analytics Measurement Protocol or Facebook CAPI. 

QIT reports warnings on those endpoints because, in the permission callback, we don't restrict it to only logged-in users, because we also need to be able to process tracking data for guest users.

`register_rest_route() with permission_callback => __return_true`

Is there a way to suppress that warning?

Or do you have another idea of how to deal with this?

**Comment by Luc45** [comment]
Certain warnings are designed to highlight potential safety risks within the code, and after review, are meant to be suppressed. If the endpoint is intentionally public, it prompts the developer to review and confirm this as a conscious decision.

Please refer to our [Security - Handling False Positives](https://woocommerce.github.io/qit-documentation/#/test-types/security?id=handling-false-positives) guide for more information. If this particular warning is intended, you can disregard it by appending the following comment to the line causing the violation:

`// nosemgrep: rule-id`

Here, ensure that `rule-id` is replaced with the specific SemGrep rule responsible for the current warning.

**Comment by Luc45** [comment]
Some of the security rules can be more noisy and prone to false-positives than others. We are continually monitoring the rules and taking feedback to ensure that our scanner provides value on every warning or error.

**Comment by alewolf** [comment]
This works. Thanks!
