### ISSUE TITLE
Cannot provide WP & WC versions as suggested in the docs

### ISSUE THREAD

**Issue by tomalec** [woocommerce/qit-cli#81]
I was trying to use QIT CLI to test specific versions of WordPress or WooCommerce.
I tried to use the exact command and versions from [the docs](https://woocommerce.github.io/qit-documentation/#/cli/running-tests?id=specifying-woocommerce-and-wordpress-versions):

```
qit run:activation google-listings-and-ads --woocommerce_version=7.0.0-rc.2 --wordpress_version=6.0.1
```

It throws 400:
```
$ qit run:activation google-listings-and-ads --woocommerce_version=7.0.0-rc.2 --wordpress_version=6.0.1
Expected return status code(s): 200. Got return status code: 400. Error message: Invalid parameter(s): wordpress_version, woocommerce_version
$ qit --version
Quality Insights Toolkit CLI 0.3.4-2-g16c3ce1a

```

**Comment by Luc45** [comment]
Howdy, we support the last 4 stables and latest release-candidate of WooCommerce.

You can run `qit run:activation --help` to see the available versions. For scripts, it's preferred to use either `stable` or `rc` as version, as they are fixed. Use the specific version only when running manually, eg: `--woocommerce_version=8.0.0`, etc

![image](https://github.com/woocommerce/qit-cli/assets/9341686/b8d7253b-5ce3-4d3c-8e94-f460e3380048)

**Comment by Luc45** [comment]
I've update the docs to reflect that, thanks, @tomalec !
