### ISSUE TITLE
Docs install command incorrect

### ISSUE THREAD

**Issue by BrianHenryIE** [woocommerce/qit-cli#88]
[At https://woocommerce.github.io/qit-documentation/#/](https://woocommerce.github.io/qit-documentation/#/?id=quick-start-guide)

```
composer install woocommerce/qit-cli
```

should be 

```
composer require woocommerce/qit-cli --dev
```

**Comment by Luc45** [comment]
Thank you, I've tweaked the docs to suggest the `--dev` flag. I don't know how this slipped by us. :thinking:
