### ISSUE TITLE
There are no commands defined in the "run" namespace.

### ISSUE THREAD

**Issue by developer53** [woocommerce/qit-cli#93]
I have install the qit by composer and also authenticate as per defined method. But whenever I run qit run:e2e <my-extention> it gives an error.

"There are no commands defined in the "run" namespace."

**Comment by Uzair-Ahmed29** [comment]
having Same issue when running e2e test.

**Comment by Luc45** [comment]
@developer53 @Uzair-Ahmed29 is this still happening?

If so, you might want to try to re-authenticate:
- Delete the QIT config dir (you can find it with `./vendor/bin/qit qit:dir`)
- Run `./vendor/bin/qit -vvv`. `-vvv` will enable verbose mode that will show what's happening under the hood, which might be helpful to debug

**Comment by Luc45** [comment]
This happens when the CLI can't communicate with the backend service. This can be a temporary hiccup, but if it's persistent I'd recommend resetting as mentioned above.

Closing this for now, feel free to reopen if needed.
